"""Setting and configuration endpoints."""

from . import (
    active_directory_config,
    business_unit_regions,
    business_unit_user_assigns,
    business_units,
    categories,
    domain_users,
    email_config,
    organizational_units,
    pages,
    priorities,
    request_status,
    request_types,
    roles,
    service_sections,
    sla_configs,
    system_messages,
    tags,
    user_custom_views,
    users,
)

__all__ = [
    "active_directory_config",
    "business_unit_regions",
    "business_unit_user_assigns",
    "business_units",
    "categories",
    "domain_users",
    "email_config",
    "organizational_units",
    "pages",
    "priorities",
    "request_status",
    "request_types",
    "roles",
    "service_sections",
    "sla_configs",
    "system_messages",
    "tags",
    "user_custom_views",
    "users",
]
