[mypy]
plugins = sqlalchemy.ext.mypy.plugin
exclude = ^repositories/
disable_error_code = import-untyped

[mypy-api.repositories.reporting.reporting_query_repository]
ignore_errors = True

[mypy-apscheduler.*]
ignore_missing_imports = True

[mypy-ldap3]
ignore_missing_imports = True

[mypy-ldap3.*]
ignore_missing_imports = True

[mypy-geoip2]
ignore_missing_imports = True

[mypy-geoip2.*]
ignore_missing_imports = True
