"""convert_user_sessions_id_to_uuid

Revision ID: 00b4c333306f
Revises: a64b786464a0
Create Date: 2025-12-27 10:14:09.066880+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "00b4c333306f"
down_revision = "a64b786464a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CRITICAL: This migration converts user_sessions.id from INTEGER to UUID
    # Since this is a breaking change, we'll clear existing sessions and auth tokens
    # Users will need to re-authenticate after this migration

    # Step 1: Delete all auth_tokens (they reference old integer session IDs)
    op.execute("DELETE FROM auth_tokens")

    # Step 2: Delete all user_sessions (will get new UUID primary keys)
    op.execute("DELETE FROM user_sessions")

    # Step 3: Convert auth_tokens.session_id from INTEGER to UUID
    op.alter_column(
        "auth_tokens",
        "session_id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=True,
        postgresql_using="NULL::UUID",  # Set all to NULL since we deleted tokens
    )

    # Step 4: Convert user_sessions.id from INTEGER to UUID (PRIMARY KEY)
    # Drop and recreate the sequence
    op.execute("DROP SEQUENCE IF EXISTS user_sessions_id_seq CASCADE")

    op.alter_column(
        "user_sessions",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="NULL::UUID",  # Placeholder (no rows exist after DELETE)
    )

    # Step 5: Apply other schema changes (server defaults)
    op.alter_column(
        "desktop_sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "web_sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CRITICAL: Downgrade also requires clearing sessions/tokens
    # since we can't convert UUID back to sequential integers

    # Step 1: Delete all auth_tokens and user_sessions
    op.execute("DELETE FROM auth_tokens")
    op.execute("DELETE FROM user_sessions")

    # Step 2: Restore server defaults
    op.alter_column(
        "web_sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "desktop_sessions",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )

    # Step 3: Convert user_sessions.id back to INTEGER with sequence
    op.alter_column(
        "user_sessions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="NULL::INTEGER",  # No rows exist after DELETE
    )

    # Recreate the sequence
    op.execute("CREATE SEQUENCE user_sessions_id_seq OWNED BY user_sessions.id")
    op.execute(
        "ALTER TABLE user_sessions ALTER COLUMN id SET DEFAULT nextval('user_sessions_id_seq')"
    )

    # Step 4: Convert auth_tokens.session_id back to INTEGER
    op.alter_column(
        "auth_tokens",
        "session_id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=True,
        postgresql_using="NULL::INTEGER",  # No rows exist after DELETE
    )
    # ### end Alembic commands ###
