"""2025_12_05_replace_smb_with_minio_storage

Revision ID: 55e01689ab91
Revises:
Create Date: 2025-12-05 18:58:47.660701+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "55e01689ab91"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename smb_path to minio_object_key
    op.alter_column(
        "attachments",
        "smb_path",
        new_column_name="minio_object_key",
        existing_type=sa.String(length=500),
        existing_nullable=True,
    )

    # Rename thumbnail_smb_path to minio_thumbnail_key
    op.alter_column(
        "attachments",
        "thumbnail_smb_path",
        new_column_name="minio_thumbnail_key",
        existing_type=sa.String(length=500),
        existing_nullable=True,
    )

    # Add bucket_name column
    op.add_column(
        "attachments", sa.Column("bucket_name", sa.String(length=100), nullable=True)
    )

    # Add celery_task_id column
    op.add_column(
        "attachments", sa.Column("celery_task_id", sa.String(length=255), nullable=True)
    )

    # Set default bucket name for existing records
    op.execute(
        "UPDATE attachments SET bucket_name = 'servicecatalog-files' WHERE bucket_name IS NULL"
    )

    # Create indexes
    op.create_index(
        "ix_attachments_celery_task_id", "attachments", ["celery_task_id"], unique=False
    )
    op.create_index(
        "ix_attachments_upload_status", "attachments", ["upload_status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index("ix_attachments_upload_status", table_name="attachments")
    op.drop_index("ix_attachments_celery_task_id", table_name="attachments")

    # Drop new columns
    op.drop_column("attachments", "celery_task_id")
    op.drop_column("attachments", "bucket_name")

    # Rename minio_thumbnail_key back to thumbnail_smb_path
    op.alter_column(
        "attachments",
        "minio_thumbnail_key",
        new_column_name="thumbnail_smb_path",
        existing_type=sa.String(length=500),
        existing_nullable=True,
    )

    # Rename minio_object_key back to smb_path
    op.alter_column(
        "attachments",
        "minio_object_key",
        new_column_name="smb_path",
        existing_type=sa.String(length=500),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
