"""add_notification_events_table

Revision ID: 0c06f3ef8cda
Revises: 23996897812a
Create Date: 2025-12-31 06:49:04.579099+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "0c06f3ef8cda"
down_revision = "23996897812a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notification_events_created_at",
        "notification_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_delivered_at",
        "notification_events",
        ["delivered_at"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_event_type",
        "notification_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_request_id",
        "notification_events",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_user_id",
        "notification_events",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_notification_events_user_pending",
        "notification_events",
        ["user_id", "delivered_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notification_events_user_pending", table_name="notification_events"
    )
    op.drop_index("ix_notification_events_user_id", table_name="notification_events")
    op.drop_index("ix_notification_events_request_id", table_name="notification_events")
    op.drop_index("ix_notification_events_event_type", table_name="notification_events")
    op.drop_index(
        "ix_notification_events_delivered_at", table_name="notification_events"
    )
    op.drop_index("ix_notification_events_created_at", table_name="notification_events")
    op.drop_table("notification_events")
    # ### end Alembic commands ###
