"""make_remote_access_request_id_nullable

Revision ID: 1c68cbf9d199
Revises: 963476071f2c
Create Date: 2025-12-27 14:46:31.658943+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c68cbf9d199"
down_revision = "963476071f2c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "remote_access_sessions", "request_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "remote_access_sessions", "request_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
