"""add remote access tables for screen sharing and control

Revision ID: 1620d067d777
Revises: cfa42ee823ae
Create Date: 2025-12-19 00:28:54.065427+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "1620d067d777"
down_revision = "cfa42ee823ae"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "remote_access_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=False),
        sa.Column("requester_id", sa.UUID(), nullable=False),
        sa.Column(
            "status", sa.String(length=20), server_default="pending", nullable=False
        ),
        sa.Column(
            "requested_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("control_enabled", sa.Boolean(), nullable=False),
        sa.Column("clipboard_enabled", sa.Boolean(), nullable=False),
        sa.Column("clipboard_sync_count", sa.Integer(), nullable=False),
        sa.Column("uac_prompt_count", sa.Integer(), nullable=False),
        sa.Column("mouse_click_count", sa.Integer(), nullable=False),
        sa.Column("key_press_count", sa.Integer(), nullable=False),
        sa.Column("end_reason", sa.String(length=50), nullable=True),
        sa.Column("quality_preset", sa.String(length=20), nullable=False),
        sa.Column("ice_connection_state", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_remote_sessions_agent_id",
        "remote_access_sessions",
        ["agent_id"],
        unique=False,
    )
    op.create_index(
        "ix_remote_sessions_created_at",
        "remote_access_sessions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_remote_sessions_request_id",
        "remote_access_sessions",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_remote_sessions_requester_id",
        "remote_access_sessions",
        ["requester_id"],
        unique=False,
    )
    op.create_index(
        "ix_remote_sessions_status", "remote_access_sessions", ["status"], unique=False
    )
    op.create_table(
        "remote_access_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("event_data", sa.JSON(), nullable=True),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("actor_type", sa.String(length=20), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["remote_access_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_remote_events_session_id",
        "remote_access_events",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        "ix_remote_events_timestamp",
        "remote_access_events",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "ix_remote_events_type", "remote_access_events", ["event_type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_remote_events_type", table_name="remote_access_events")
    op.drop_index("ix_remote_events_timestamp", table_name="remote_access_events")
    op.drop_index("ix_remote_events_session_id", table_name="remote_access_events")
    op.drop_table("remote_access_events")
    op.drop_index("ix_remote_sessions_status", table_name="remote_access_sessions")
    op.drop_index(
        "ix_remote_sessions_requester_id", table_name="remote_access_sessions"
    )
    op.drop_index("ix_remote_sessions_request_id", table_name="remote_access_sessions")
    op.drop_index("ix_remote_sessions_created_at", table_name="remote_access_sessions")
    op.drop_index("ix_remote_sessions_agent_id", table_name="remote_access_sessions")
    op.drop_table("remote_access_sessions")
    # ### end Alembic commands ###
