"""add_client_versions_table

Revision ID: 629111e3f517
Revises: 1c68cbf9d199
Create Date: 2025-12-27 15:25:16.828923+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "629111e3f517"
down_revision = "1c68cbf9d199"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_string", sa.String(length=50), nullable=False),
        sa.Column(
            "platform",
            sa.String(length=20),
            server_default=sa.text("'desktop'"),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "is_latest", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_enforced", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("release_notes", sa.Text(), nullable=True),
        sa.Column("released_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version_string"),
    )
    op.create_index(
        "ix_client_versions_is_active", "client_versions", ["is_active"], unique=False
    )
    op.create_index(
        "ix_client_versions_is_enforced",
        "client_versions",
        ["is_enforced"],
        unique=False,
    )
    op.create_index(
        "ix_client_versions_is_latest", "client_versions", ["is_latest"], unique=False
    )
    op.create_index(
        "ix_client_versions_order_index",
        "client_versions",
        ["order_index"],
        unique=False,
    )
    op.create_index(
        "ix_client_versions_platform", "client_versions", ["platform"], unique=False
    )
    op.create_index(
        "ix_client_versions_platform_active",
        "client_versions",
        ["platform", "is_active"],
        unique=False,
    )
    op.create_index(
        "ix_client_versions_version_string",
        "client_versions",
        ["version_string"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_client_versions_version_string", table_name="client_versions")
    op.drop_index("ix_client_versions_platform_active", table_name="client_versions")
    op.drop_index("ix_client_versions_platform", table_name="client_versions")
    op.drop_index("ix_client_versions_order_index", table_name="client_versions")
    op.drop_index("ix_client_versions_is_latest", table_name="client_versions")
    op.drop_index("ix_client_versions_is_enforced", table_name="client_versions")
    op.drop_index("ix_client_versions_is_active", table_name="client_versions")
    op.drop_table("client_versions")
    # ### end Alembic commands ###
