"""add_is_active_is_deleted_to_business_units_and_regions

Revision ID: 64541d8224bf
Revises: 1cf4dd885635
Create Date: 2025-12-05 21:53:43.996127+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "64541d8224bf"
down_revision = "1cf4dd885635"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chat_approvals_request_id"), table_name="chat_attachment_approvals"
    )
    op.drop_index(
        op.f("ix_chat_approvals_status"), table_name="chat_attachment_approvals"
    )
    op.drop_table("chat_attachment_approvals")
    op.add_column(
        "business_unit_regions",
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
    )
    op.add_column(
        "business_unit_regions",
        sa.Column("is_deleted", sa.Boolean(), nullable=True, server_default="false"),
    )
    # Set existing rows to default values
    op.execute("UPDATE business_unit_regions SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE business_unit_regions SET is_deleted = false WHERE is_deleted IS NULL")
    # Now alter the columns to be NOT NULL
    op.alter_column("business_unit_regions", "is_active", nullable=False)
    op.alter_column("business_unit_regions", "is_deleted", nullable=False)
    op.create_index(
        "ix_business_unit_regions_is_active",
        "business_unit_regions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        "ix_business_unit_regions_is_deleted",
        "business_unit_regions",
        ["is_deleted"],
        unique=False,
    )
    op.add_column(
        "business_units",
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
    )
    op.add_column(
        "business_units",
        sa.Column("is_deleted", sa.Boolean(), nullable=True, server_default="false"),
    )
    # Set existing rows to default values
    op.execute("UPDATE business_units SET is_active = true WHERE is_active IS NULL")
    op.execute("UPDATE business_units SET is_deleted = false WHERE is_deleted IS NULL")
    # Now alter the columns to be NOT NULL
    op.alter_column("business_units", "is_active", nullable=False)
    op.alter_column("business_units", "is_deleted", nullable=False)
    op.create_index(
        "ix_business_units_is_active", "business_units", ["is_active"], unique=False
    )
    op.create_index(
        "ix_business_units_is_deleted", "business_units", ["is_deleted"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_business_units_is_deleted", table_name="business_units")
    op.drop_index("ix_business_units_is_active", table_name="business_units")
    op.drop_column("business_units", "is_deleted")
    op.drop_column("business_units", "is_active")
    op.drop_index(
        "ix_business_unit_regions_is_deleted", table_name="business_unit_regions"
    )
    op.drop_index(
        "ix_business_unit_regions_is_active", table_name="business_unit_regions"
    )
    op.drop_column("business_unit_regions", "is_deleted")
    op.drop_column("business_unit_regions", "is_active")
    op.create_table(
        "chat_attachment_approvals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "request_id", sa.CHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            "total_attachments", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "approval_status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("approved_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "approved_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("rejection_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
            name=op.f("chat_attachment_approvals_approved_by_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["service_requests.id"],
            name=op.f("chat_attachment_approvals_request_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("chat_attachment_approvals_pkey")),
    )
    op.create_index(
        op.f("ix_chat_approvals_status"),
        "chat_attachment_approvals",
        ["approval_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chat_approvals_request_id"),
        "chat_attachment_approvals",
        ["request_id"],
        unique=False,
    )
    # ### end Alembic commands ###
