"""create domain_users table for AD sync

Revision ID: a459c70c9b47
Revises: 55a0087208e8
Create Date: 2025-12-08 09:15:34.321866+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a459c70c9b47"
down_revision = "55a0087208e8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domain_users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("direct_manager_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("office", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "ix_domain_users_created_at", "domain_users", ["created_at"], unique=False
    )
    op.create_index(
        "ix_domain_users_display_name", "domain_users", ["display_name"], unique=False
    )
    op.create_index("ix_domain_users_email", "domain_users", ["email"], unique=False)
    op.create_index(
        "ix_domain_users_username", "domain_users", ["username"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_domain_users_username", table_name="domain_users")
    op.drop_index("ix_domain_users_email", table_name="domain_users")
    op.drop_index("ix_domain_users_display_name", table_name="domain_users")
    op.drop_index("ix_domain_users_created_at", table_name="domain_users")
    op.drop_table("domain_users")
    # ### end Alembic commands ###
