"""add sub-tasks tables

Revision ID: f5f80e3e1dbd
Revises: 4f6386fea68d
Create Date: 2025-12-06 09:41:01.059940+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "f5f80e3e1dbd"
down_revision = "4f6386fea68d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sub_tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column(
            "title", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("priority_id", sa.Integer(), nullable=False),
        sa.Column("assigned_to_section_id", sa.Integer(), nullable=True),
        sa.Column("assigned_to_technician_id", sa.UUID(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column("estimated_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column(
            "blocked_reason",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_section_id"],
            ["service_sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_technician_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["priority_id"],
            ["priorities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["request_statuses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sub_tasks_assigned_to_section_id",
        "sub_tasks",
        ["assigned_to_section_id"],
        unique=False,
    )
    op.create_index(
        "ix_sub_tasks_assigned_to_technician_id",
        "sub_tasks",
        ["assigned_to_technician_id"],
        unique=False,
    )
    op.create_index(
        "ix_sub_tasks_created_at", "sub_tasks", ["created_at"], unique=False
    )
    op.create_index(
        "ix_sub_tasks_created_by", "sub_tasks", ["created_by"], unique=False
    )
    op.create_index("ix_sub_tasks_due_date", "sub_tasks", ["due_date"], unique=False)
    op.create_index("ix_sub_tasks_is_active", "sub_tasks", ["is_active"], unique=False)
    op.create_index(
        "ix_sub_tasks_is_blocked", "sub_tasks", ["is_blocked"], unique=False
    )
    op.create_index(
        "ix_sub_tasks_is_deleted", "sub_tasks", ["is_deleted"], unique=False
    )
    op.create_index(
        "ix_sub_tasks_priority_id", "sub_tasks", ["priority_id"], unique=False
    )
    op.create_index(
        "ix_sub_tasks_request_id", "sub_tasks", ["request_id"], unique=False
    )
    op.create_index(
        "ix_sub_tasks_request_status",
        "sub_tasks",
        ["request_id", "status_id"],
        unique=False,
    )
    op.create_index("ix_sub_tasks_status_id", "sub_tasks", ["status_id"], unique=False)
    op.create_table(
        "sub_task_attachments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub_task_id", sa.UUID(), nullable=False),
        sa.Column("uploaded_by", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "mime_type", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "file_hash", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "minio_object_key",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column(
            "bucket_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "celery_task_id",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column(
            "upload_status", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "temp_local_path",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=True,
        ),
        sa.Column("is_corrupted", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sub_task_id"], ["sub_tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sub_task_attachments_created_at",
        "sub_task_attachments",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        "ix_sub_task_attachments_sub_task_id",
        "sub_task_attachments",
        ["sub_task_id"],
        unique=False,
    )
    op.create_index(
        "ix_sub_task_attachments_upload_status",
        "sub_task_attachments",
        ["upload_status"],
        unique=False,
    )
    op.create_index(
        "ix_sub_task_attachments_uploaded_by",
        "sub_task_attachments",
        ["uploaded_by"],
        unique=False,
    )
    op.create_table(
        "sub_task_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sub_task_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sub_task_id"], ["sub_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_sub_task_notes_created_at", "sub_task_notes", ["created_at"], unique=False
    )
    op.create_index(
        "ix_sub_task_notes_created_by", "sub_task_notes", ["created_by"], unique=False
    )
    op.create_index(
        "ix_sub_task_notes_sub_task_id", "sub_task_notes", ["sub_task_id"], unique=False
    )
    op.alter_column(
        "request_statuses",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "request_statuses",
        "name_ar",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "request_statuses",
        "name_ar",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "request_statuses",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.drop_index("ix_sub_task_notes_sub_task_id", table_name="sub_task_notes")
    op.drop_index("ix_sub_task_notes_created_by", table_name="sub_task_notes")
    op.drop_index("ix_sub_task_notes_created_at", table_name="sub_task_notes")
    op.drop_table("sub_task_notes")
    op.drop_index(
        "ix_sub_task_attachments_uploaded_by", table_name="sub_task_attachments"
    )
    op.drop_index(
        "ix_sub_task_attachments_upload_status", table_name="sub_task_attachments"
    )
    op.drop_index(
        "ix_sub_task_attachments_sub_task_id", table_name="sub_task_attachments"
    )
    op.drop_index(
        "ix_sub_task_attachments_created_at", table_name="sub_task_attachments"
    )
    op.drop_table("sub_task_attachments")
    op.drop_index("ix_sub_tasks_status_id", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_request_status", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_request_id", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_priority_id", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_is_deleted", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_is_blocked", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_is_active", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_due_date", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_created_by", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_created_at", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_assigned_to_technician_id", table_name="sub_tasks")
    op.drop_index("ix_sub_tasks_assigned_to_section_id", table_name="sub_tasks")
    op.drop_table("sub_tasks")
    # ### end Alembic commands ###
