"""add_app_version_to_user_sessions

Revision ID: 9c858bb66f4b
Revises: a29b475540c8
Create Date: 2025-12-27 07:31:10.681015+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "9c858bb66f4b"
down_revision = "a29b475540c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_sessions", sa.Column("app_version", sa.String(length=50), nullable=True)
    )
    op.drop_index(
        op.f("uq_whatsapp_batch_request_created"),
        table_name="whatsapp_batches",
        postgresql_where="((batch_type)::text = 'request_created'::text)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_whatsapp_batch_request_created"),
        "whatsapp_batches",
        ["request_id", "batch_type"],
        unique=True,
        postgresql_where="((batch_type)::text = 'request_created'::text)",
    )
    op.drop_column("user_sessions", "app_version")
    # ### end Alembic commands ###
