"""remove_user_sessions_convert_to_uuid

Revision ID: 963476071f2c
Revises: 00b4c333306f
Create Date: 2025-12-27 10:39:09.739520+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "963476071f2c"
down_revision = "00b4c333306f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CRITICAL: Remove user_sessions table and convert desktop/web sessions to UUID
    # All existing sessions will be cleared - users must re-authenticate

    # Step 1: Clear all auth_tokens (reference desktop/web sessions)
    op.execute("DELETE FROM auth_tokens")

    # Step 2: Clear all desktop and web sessions
    op.execute("DELETE FROM desktop_sessions")
    op.execute("DELETE FROM web_sessions")

    # Step 3: Drop user_sessions table (no longer needed)
    op.drop_index(
        op.f("idx_user_sessions_device_fingerprint"), table_name="user_sessions"
    )
    op.drop_index(op.f("ix_sessions_is_active"), table_name="user_sessions")
    op.drop_index(op.f("ix_sessions_last_heartbeat"), table_name="user_sessions")
    op.drop_index(op.f("ix_sessions_session_type_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_sessions_user_active"), table_name="user_sessions")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="user_sessions")
    op.drop_table("user_sessions")

    # Step 4: Convert desktop_sessions.id to UUID
    op.execute("DROP SEQUENCE IF EXISTS desktop_sessions_id_seq CASCADE")
    op.alter_column(
        "desktop_sessions",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="NULL::UUID",  # No rows exist after DELETE
    )

    # Step 5: Convert web_sessions.id to UUID
    op.execute("DROP SEQUENCE IF EXISTS web_sessions_id_seq CASCADE")
    op.alter_column(
        "web_sessions",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
        postgresql_using="NULL::UUID",  # No rows exist after DELETE
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # CRITICAL: Downgrade also requires clearing sessions
    # Cannot convert UUID back to sequential integers with existing data

    # Step 1: Clear all sessions and tokens
    op.execute("DELETE FROM auth_tokens")
    op.execute("DELETE FROM desktop_sessions")
    op.execute("DELETE FROM web_sessions")

    # Step 2: Convert web_sessions.id back to INTEGER
    op.alter_column(
        "web_sessions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="NULL::INTEGER",
    )
    op.execute("CREATE SEQUENCE web_sessions_id_seq OWNED BY web_sessions.id")
    op.execute(
        "ALTER TABLE web_sessions ALTER COLUMN id SET DEFAULT nextval('web_sessions_id_seq')"
    )

    # Step 3: Convert desktop_sessions.id back to INTEGER
    op.alter_column(
        "desktop_sessions",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        postgresql_using="NULL::INTEGER",
    )
    op.execute("CREATE SEQUENCE desktop_sessions_id_seq OWNED BY desktop_sessions.id")
    op.execute(
        "ALTER TABLE desktop_sessions ALTER COLUMN id SET DEFAULT nextval('desktop_sessions_id_seq')"
    )
    op.create_table(
        "user_sessions",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("session_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "ip_address", sa.VARCHAR(length=45), autoincrement=False, nullable=False
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "authenticated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "auth_method",
            sa.VARCHAR(length=50),
            server_default=sa.text("'passwordless'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_auth_refresh",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "device_fingerprint",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_heartbeat",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "app_version", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_sessions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_sessions_pkey")),
    )
    op.create_index(
        op.f("ix_sessions_user_id"), "user_sessions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_sessions_user_active"),
        "user_sessions",
        ["user_id", "is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_session_type_id"),
        "user_sessions",
        ["session_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_last_heartbeat"),
        "user_sessions",
        ["last_heartbeat"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sessions_is_active"), "user_sessions", ["is_active"], unique=False
    )
    op.create_index(
        op.f("idx_user_sessions_device_fingerprint"),
        "user_sessions",
        ["device_fingerprint"],
        unique=False,
    )
    # ### end Alembic commands ###
