"""add visible_on_requester_page to request_statuses

Revision ID: 55a0087208e8
Revises: 8817a9e16cfd
Create Date: 2025-12-07 13:31:20.287411+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "55a0087208e8"
down_revision = "8817a9e16cfd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_statuses",
        sa.Column(
            "visible_on_requester_page",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("true"),
        ),
    )
    op.create_index(
        "ix_request_statuses_visible_on_requester_page",
        "request_statuses",
        ["visible_on_requester_page"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_request_statuses_visible_on_requester_page", table_name="request_statuses"
    )
    op.drop_column("request_statuses", "visible_on_requester_page")
    # ### end Alembic commands ###
