"""make whatsapp batch message ids nullable for request_created support

Revision ID: 1271b6c45133
Revises: 48c19b92a806
Create Date: 2025-12-26 12:34:36.626613+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1271b6c45133"
down_revision = "48c19b92a806"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "business_units",
        "whatsapp_outshift_interval_minutes",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "whatsapp_batches", "first_message_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "whatsapp_batches", "last_message_id", existing_type=sa.UUID(), nullable=True
    )

    # Add partial unique constraint for request_created batches
    # This ensures only one request_created batch per request
    op.execute(
        """
        CREATE UNIQUE INDEX uq_whatsapp_batch_request_created
        ON whatsapp_batches (request_id, batch_type)
        WHERE batch_type = 'request_created'
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the partial unique constraint
    op.execute("DROP INDEX IF EXISTS uq_whatsapp_batch_request_created")

    op.alter_column(
        "whatsapp_batches", "last_message_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "whatsapp_batches", "first_message_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "business_units",
        "whatsapp_outshift_interval_minutes",
        existing_type=sa.INTEGER(),
        server_default=sa.text("30"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
