"""add_remote_session_durable_state

Revision ID: 5acf4bd0aa7c
Revises: 0c06f3ef8cda
Create Date: 2025-12-31 06:54:02.163626+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "5acf4bd0aa7c"
down_revision = "0c06f3ef8cda"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "remote_access_sessions",
        sa.Column(
            "status", sa.String(length=20), server_default="active", nullable=False
        ),
    )
    op.add_column(
        "remote_access_sessions",
        sa.Column(
            "control_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "remote_access_sessions", sa.Column("ended_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "remote_access_sessions",
        sa.Column("end_reason", sa.String(length=50), nullable=True),
    )
    op.create_index(
        "ix_remote_sessions_status", "remote_access_sessions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_remote_sessions_status", table_name="remote_access_sessions")
    op.drop_column("remote_access_sessions", "end_reason")
    op.drop_column("remote_access_sessions", "ended_at")
    op.drop_column("remote_access_sessions", "control_enabled")
    op.drop_column("remote_access_sessions", "status")
    # ### end Alembic commands ###
