"""add_whatsapp_out_of_shift_escalation_fields

Revision ID: 48c19b92a806
Revises: 197b5205b6df
Create Date: 2025-12-26 10:40:47.255654+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "48c19b92a806"
down_revision = "197b5205b6df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "whatsapp_batches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column("business_unit_id", sa.Integer(), nullable=True),
        sa.Column("first_message_id", sa.UUID(), nullable=False),
        sa.Column("last_message_id", sa.UUID(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.Column("batch_type", sa.String(length=50), nullable=False),
        sa.Column(
            "sent_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("delivery_status", sa.String(length=50), nullable=False),
        sa.Column("payload_snapshot", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["business_unit_id"], ["business_units.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["first_message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["last_message_id"], ["chat_messages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["service_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "request_id",
            "first_message_id",
            "last_message_id",
            name="uq_whatsapp_batch_message_range",
        ),
    )
    op.create_index(
        "ix_whatsapp_batches_batch_type",
        "whatsapp_batches",
        ["batch_type"],
        unique=False,
    )
    op.create_index(
        "ix_whatsapp_batches_business_unit_id",
        "whatsapp_batches",
        ["business_unit_id"],
        unique=False,
    )
    op.create_index(
        "ix_whatsapp_batches_request_id",
        "whatsapp_batches",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_whatsapp_batches_sent_at", "whatsapp_batches", ["sent_at"], unique=False
    )
    op.add_column(
        "business_units", sa.Column("working_hours", sa.JSON(), nullable=True)
    )
    op.add_column(
        "business_units",
        sa.Column("whatsapp_group_name", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "business_units",
        sa.Column("whatsapp_group_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "business_units",
        sa.Column(
            "whatsapp_outshift_interval_minutes",
            sa.Integer(),
            nullable=False,
            server_default="30",
        ),
    )
    op.add_column(
        "service_requests",
        sa.Column(
            "first_requester_message_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "service_requests",
        sa.Column("whatsapp_last_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ix_requests_bu_assignee_first_msg",
        "service_requests",
        ["business_unit_id", "assigned_to_technician_id", "first_requester_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_requests_first_requester_message_at",
        "service_requests",
        ["first_requester_message_at"],
        unique=False,
    )
    op.create_index(
        "ix_requests_whatsapp_last_sent_at",
        "service_requests",
        ["whatsapp_last_sent_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_requests_whatsapp_last_sent_at", table_name="service_requests")
    op.drop_index(
        "ix_requests_first_requester_message_at", table_name="service_requests"
    )
    op.drop_index("ix_requests_bu_assignee_first_msg", table_name="service_requests")
    op.drop_column("service_requests", "whatsapp_last_sent_at")
    op.drop_column("service_requests", "first_requester_message_at")
    op.drop_column("business_units", "whatsapp_outshift_interval_minutes")
    op.drop_column("business_units", "whatsapp_group_url")
    op.drop_column("business_units", "whatsapp_group_name")
    op.drop_column("business_units", "working_hours")
    op.drop_index("ix_whatsapp_batches_sent_at", table_name="whatsapp_batches")
    op.drop_index("ix_whatsapp_batches_request_id", table_name="whatsapp_batches")
    op.drop_index("ix_whatsapp_batches_business_unit_id", table_name="whatsapp_batches")
    op.drop_index("ix_whatsapp_batches_batch_type", table_name="whatsapp_batches")
    op.drop_table("whatsapp_batches")
    # ### end Alembic commands ###
