"""add_request_types_table

Revision ID: 0d75041e2e23
Revises: 1620d067d777
Create Date: 2025-12-25 22:00:49.106199+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d75041e2e23"
down_revision = "1620d067d777"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "ix_request_types_is_active", "request_types", ["is_active"], unique=False
    )
    op.create_index("ix_request_types_name", "request_types", ["name"], unique=True)
    op.add_column(
        "service_requests", sa.Column("request_type_id", sa.Integer(), nullable=True)
    )
    op.create_index(
        "ix_requests_request_type_id",
        "service_requests",
        ["request_type_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "service_requests", "request_types", ["request_type_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "service_requests", type_="foreignkey")
    op.drop_index("ix_requests_request_type_id", table_name="service_requests")
    op.drop_column("service_requests", "request_type_id")
    op.drop_index("ix_request_types_name", table_name="request_types")
    op.drop_index("ix_request_types_is_active", table_name="request_types")
    op.drop_table("request_types")
    # ### end Alembic commands ###
