"""add_installer_metadata_to_client_versions

Revision ID: c68d306045ff
Revises: 629111e3f517
Create Date: 2025-12-27 18:27:22.184953+00:00

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "c68d306045ff"
down_revision = "629111e3f517"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "client_versions",
        sa.Column("installer_url", sa.String(length=500), nullable=True),
    )
    op.add_column(
        "client_versions",
        sa.Column(
            "silent_install_args",
            sa.String(length=100),
            server_default=sa.text("'/qn /norestart'"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("client_versions", "silent_install_args")
    op.drop_column("client_versions", "installer_url")
    # ### end Alembic commands ###
