"""create system events table

Revision ID: 4f6386fea68d
Revises: bilingual_support_v1
Create Date: 2025-12-06 08:51:17.973052+00:00

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4f6386fea68d"
down_revision = "bilingual_support_v1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove server defaults from request_statuses bilingual columns
    op.alter_column(
        "request_statuses",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "request_statuses",
        "name_ar",
        existing_type=sa.VARCHAR(length=100),
        server_default=None,
        existing_nullable=False,
    )

    # Create system_events table
    op.create_table(
        'system_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_key', sa.String(50), nullable=False),
        sa.Column('event_name_en', sa.String(100), nullable=False),
        sa.Column('event_name_ar', sa.String(100), nullable=False),
        sa.Column('description_en', sa.String(500), nullable=True),
        sa.Column('description_ar', sa.String(500), nullable=True),
        sa.Column('system_message_id', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.Column('trigger_timing', sa.String(20), server_default=sa.text("'immediate'"), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('created_by', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
        sa.Column('updated_by', sa.dialects.postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=True),
        sa.ForeignKeyConstraint(['system_message_id'], ['system_messages.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes
    op.create_index('ix_system_events_event_key', 'system_events', ['event_key'], unique=True)
    op.create_index('ix_system_events_is_active', 'system_events', ['is_active'])
    op.create_index('ix_system_events_system_message_id', 'system_events', ['system_message_id'])
    op.create_index('ix_system_events_trigger_timing', 'system_events', ['trigger_timing'])
    op.create_index('ix_system_events_created_at', 'system_events', ['created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop system_events table and indexes
    op.drop_index('ix_system_events_created_at', table_name='system_events')
    op.drop_index('ix_system_events_trigger_timing', table_name='system_events')
    op.drop_index('ix_system_events_system_message_id', table_name='system_events')
    op.drop_index('ix_system_events_is_active', table_name='system_events')
    op.drop_index('ix_system_events_event_key', table_name='system_events')
    op.drop_table('system_events')

    # Restore server defaults for request_statuses
    op.alter_column(
        "request_statuses",
        "name_ar",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    op.alter_column(
        "request_statuses",
        "name_en",
        existing_type=sa.VARCHAR(length=100),
        server_default=sa.text("''::character varying"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
