"""Add composite indexes for desktop sessions

Revision ID: 2026_02_14_1534
Revises: 2026_02_14_1532-d0a0e67bbfc2
Create Date: 2026-02-14 15:34:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2026_02_14_1534'
down_revision: Union[str, None] = '2026_02_14_1532-d0a0e67bbfc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_desktop_sessions_active_heartbeat',
        'desktop_sessions',
        ['is_active', 'last_heartbeat'],
        unique=False
    )
    op.create_index(
        'ix_desktop_sessions_user_created',
        'desktop_sessions',
        ['user_id', 'created_at'],
        unique=False,
        postgresql_descending=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_desktop_sessions_user_created', table_name='desktop_sessions')
    op.drop_index('ix_desktop_sessions_active_heartbeat', table_name='desktop_sessions')
    # ### end Alembic commands ###