"""add_scheduler_management_tables

Revision ID: 680c1ba0c650
Revises: add_chat_files_table
Create Date: 2026-01-15 14:54:30.552794

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '680c1ba0c650'
down_revision = 'add_chat_files_table'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('is_leader', sa.Boolean(), nullable=False),
    sa.Column('leader_since', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduler_instances_hostname_pid', 'scheduler_instances', ['hostname', 'pid'], unique=False)
    op.create_index('ix_scheduler_instances_is_leader', 'scheduler_instances', ['is_leader'], unique=False)
    op.create_index('ix_scheduler_instances_last_heartbeat', 'scheduler_instances', ['last_heartbeat'], unique=False)
    op.create_table('scheduler_job_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_scheduler_job_types_name', 'scheduler_job_types', ['name'], unique=True)
    op.create_table('task_functions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('handler_path', sa.String(length=500), nullable=False),
    sa.Column('handler_type', sa.String(length=20), nullable=False),
    sa.Column('queue', sa.String(length=50), nullable=True),
    sa.Column('default_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_task_functions_is_active', 'task_functions', ['is_active'], unique=False)
    op.create_index('ix_task_functions_name', 'task_functions', ['name'], unique=True)
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_function_id', sa.Integer(), nullable=False),
    sa.Column('job_type_id', sa.Integer(), nullable=False),
    sa.Column('schedule_config', sa.JSON(), nullable=False),
    sa.Column('task_args', sa.JSON(), nullable=True),
    sa.Column('max_instances', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.Column('last_run_time', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_type_id'], ['scheduler_job_types.id'], ),
    sa.ForeignKeyConstraint(['task_function_id'], ['task_functions.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_jobs_created_at', 'scheduled_jobs', ['created_at'], unique=False)
    op.create_index('ix_scheduled_jobs_is_enabled', 'scheduled_jobs', ['is_enabled'], unique=False)
    op.create_index('ix_scheduled_jobs_next_run_time', 'scheduled_jobs', ['next_run_time'], unique=False)
    op.create_index('ix_scheduled_jobs_task_function_id', 'scheduled_jobs', ['task_function_id'], unique=False)
    op.create_table('scheduled_job_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('error_traceback', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('scheduler_instance_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduler_instance_id'], ['scheduler_instances.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scheduled_job_executions_job_id', 'scheduled_job_executions', ['job_id'], unique=False)
    op.create_index('ix_scheduled_job_executions_job_status', 'scheduled_job_executions', ['job_id', 'status'], unique=False)
    op.create_index('ix_scheduled_job_executions_started_at', 'scheduled_job_executions', ['started_at'], unique=False)
    op.create_index('ix_scheduled_job_executions_status', 'scheduled_job_executions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scheduled_job_executions_status', table_name='scheduled_job_executions')
    op.drop_index('ix_scheduled_job_executions_started_at', table_name='scheduled_job_executions')
    op.drop_index('ix_scheduled_job_executions_job_status', table_name='scheduled_job_executions')
    op.drop_index('ix_scheduled_job_executions_job_id', table_name='scheduled_job_executions')
    op.drop_table('scheduled_job_executions')
    op.drop_index('ix_scheduled_jobs_task_function_id', table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_next_run_time', table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_is_enabled', table_name='scheduled_jobs')
    op.drop_index('ix_scheduled_jobs_created_at', table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_index('ix_task_functions_name', table_name='task_functions')
    op.drop_index('ix_task_functions_is_active', table_name='task_functions')
    op.drop_table('task_functions')
    op.drop_index('ix_scheduler_job_types_name', table_name='scheduler_job_types')
    op.drop_table('scheduler_job_types')
    op.drop_index('ix_scheduler_instances_last_heartbeat', table_name='scheduler_instances')
    op.drop_index('ix_scheduler_instances_is_leader', table_name='scheduler_instances')
    op.drop_index('ix_scheduler_instances_hostname_pid', table_name='scheduler_instances')
    op.drop_table('scheduler_instances')
    # ### end Alembic commands ###