"""add_email_configs_table

Revision ID: cf35d6a83683
Revises: c3a70234d95b
Create Date: 2026-01-31 21:51:44.294613

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'cf35d6a83683'
down_revision = 'c3a70234d95b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('smtp_host', sa.String(length=255), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=False),
    sa.Column('smtp_user', sa.String(length=255), nullable=False),
    sa.Column('smtp_from', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('smtp_tls', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_email_configs_is_active', 'email_configs', ['is_active'], unique=False)
    op.create_index('ix_email_configs_name', 'email_configs', ['name'], unique=False)
    op.create_index('ix_email_configs_unique_active', 'email_configs', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_configs_unique_active', table_name='email_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_email_configs_name', table_name='email_configs')
    op.drop_index('ix_email_configs_is_active', table_name='email_configs')
    op.drop_table('email_configs')
    # ### end Alembic commands ###