"""add_active_directory_config_table

Revision ID: b1a31caf3f2b
Revises: 0e6f2efb6840
Create Date: 2026-01-31 14:24:14.528193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a31caf3f2b'
down_revision = '0e6f2efb6840'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_directory_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('use_ssl', sa.Boolean(), nullable=False),
    sa.Column('ldap_username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('base_dn', sa.String(length=500), nullable=False),
    sa.Column('desired_ous', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_active_directory_configs_is_active', 'active_directory_configs', ['is_active'], unique=False)
    op.create_index('ix_active_directory_configs_name', 'active_directory_configs', ['name'], unique=False)
    op.create_index('ix_active_directory_configs_unique_active', 'active_directory_configs', ['is_active'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_active_directory_configs_unique_active', table_name='active_directory_configs', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_active_directory_configs_name', table_name='active_directory_configs')
    op.drop_index('ix_active_directory_configs_is_active', table_name='active_directory_configs')
    op.drop_table('active_directory_configs')
    # ### end Alembic commands ###