"""add organizational_units table

Revision ID: 74d5a2d9ebf5
Revises: ad32fa032125
Create Date: 2026-01-15 20:48:36.887006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74d5a2d9ebf5'
down_revision = 'ad32fa032125'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizational_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ou_name', sa.String(length=100), nullable=False),
    sa.Column('ou_dn', sa.String(length=500), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ou_name')
    )
    op.create_index('ix_organizational_units_is_enabled', 'organizational_units', ['is_enabled'], unique=False)
    op.create_index('ix_organizational_units_last_synced_at', 'organizational_units', ['last_synced_at'], unique=False)
    op.create_index('ix_organizational_units_ou_name', 'organizational_units', ['ou_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_organizational_units_ou_name', table_name='organizational_units')
    op.drop_index('ix_organizational_units_last_synced_at', table_name='organizational_units')
    op.drop_index('ix_organizational_units_is_enabled', table_name='organizational_units')
    op.drop_table('organizational_units')
    # ### end Alembic commands ###