"""Add client_temp_id to chat_messages for optimistic UI updates

Revision ID: 2c583e0c38e6
Revises: b89ec16e2cad
Create Date: 2026-02-14 14:41:13.591929

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2c583e0c38e6'
down_revision = 'b89ec16e2cad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credential_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.JSON(), nullable=False),
    sa.Column('vault_ref', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_credentials_created_at', 'credentials', ['created_at'], unique=False)
    op.create_index('ix_credentials_enabled', 'credentials', ['enabled'], unique=False)
    op.create_index('ix_credentials_name', 'credentials', ['name'], unique=False)
    op.create_index('ix_credentials_type', 'credentials', ['credential_type'], unique=False)
    op.create_table('deployment_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('claimed_by', sa.String(length=255), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deployment_jobs_created_at', 'deployment_jobs', ['created_at'], unique=False)
    op.create_index('ix_deployment_jobs_job_type', 'deployment_jobs', ['job_type'], unique=False)
    op.create_index('ix_deployment_jobs_status', 'deployment_jobs', ['status'], unique=False)
    op.create_index('ix_deployment_jobs_status_created', 'deployment_jobs', ['status', 'created_at'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=50), server_default=sa.text("'discovered'"), nullable=False),
    sa.Column('discovery_source', sa.String(length=50), nullable=False),
    sa.Column('ad_computer_dn', sa.String(length=500), nullable=True),
    sa.Column('desktop_session_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['desktop_session_id'], ['desktop_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_devices_created_at', 'devices', ['created_at'], unique=False)
    op.create_index('ix_devices_desktop_session_id', 'devices', ['desktop_session_id'], unique=False)
    op.create_index('ix_devices_discovery_source', 'devices', ['discovery_source'], unique=False)
    op.create_index('ix_devices_hostname', 'devices', ['hostname'], unique=False)
    op.create_index('ix_devices_lifecycle_state', 'devices', ['lifecycle_state'], unique=False)
    op.create_index('ix_devices_state_source', 'devices', ['lifecycle_state', 'discovery_source'], unique=False)
    op.drop_constraint(op.f('categories_section_id_fkey'), 'categories', type_='foreignkey')
    op.create_foreign_key(None, 'categories', 'sections', ['section_id'], ['id'])
    op.create_index('ix_chat_files_request_id', 'chat_files', ['request_id'], unique=False)
    op.add_column('chat_messages', sa.Column('client_temp_id', sa.String(length=100), nullable=True))
    op.create_index('ix_chat_message_request_sequence', 'chat_messages', ['request_id', 'sequence_number'], unique=True)
    op.create_index('ix_messages_request_created', 'chat_messages', ['request_id', 'created_at'], unique=False)
    op.create_index('ix_messages_request_created_desc', 'chat_messages', ['request_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_messages_request_id', 'chat_messages', ['request_id'], unique=False)
    op.create_index('ix_messages_request_sender', 'chat_messages', ['request_id', 'sender_id'], unique=False)
    op.create_index('ix_messages_request_unread', 'chat_messages', ['request_id', 'is_read'], unique=False)
    op.alter_column('chat_read_states', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='(request_id::text)::integer')
    op.create_foreign_key(None, 'chat_read_states', 'service_requests', ['request_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_notification_events_request_id', 'notification_events', ['request_id'], unique=False)
    op.create_index('ix_remote_sessions_request_id', 'remote_access_sessions', ['request_id'], unique=False)
    op.create_index('ix_request_assignees_request_id', 'request_assignees', ['request_id'], unique=False)
    op.create_index('ix_request_assignees_unique', 'request_assignees', ['request_id', 'assignee_id'], unique=True)
    op.create_index('ix_request_notes_request_created', 'request_notes', ['request_id', 'created_at'], unique=False)
    op.create_index('ix_request_notes_request_id', 'request_notes', ['request_id'], unique=False)
    op.create_index('ix_request_resolutions_request_id', 'request_resolutions', ['request_id'], unique=False)
    op.create_index('ix_screenshot_links_request_id', 'request_screenshot_links', ['request_id'], unique=False)
    op.create_unique_constraint('uq_request_screenshot_link', 'request_screenshot_links', ['request_id', 'screenshot_id'])
    op.drop_constraint(op.f('request_types_section_id_fkey'), 'request_types', type_='foreignkey')
    op.create_foreign_key(None, 'request_types', 'sections', ['section_id'], ['id'])
    op.create_index('ix_screenshots_request_id', 'screenshots', ['request_id'], unique=False)
    op.create_index('ix_requests_parent_order', 'service_requests', ['parent_task_id', 'order'], unique=False)
    op.create_index('ix_requests_parent_status', 'service_requests', ['parent_task_id', 'status_id'], unique=False)
    op.create_index('ix_requests_parent_task_id', 'service_requests', ['parent_task_id'], unique=False)
    op.alter_column('whatsapp_batches', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='(request_id::text)::integer')
    op.create_foreign_key(None, 'whatsapp_batches', 'service_requests', ['request_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'whatsapp_batches', type_='foreignkey')
    op.alter_column('whatsapp_batches', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_requests_parent_task_id', table_name='service_requests')
    op.drop_index('ix_requests_parent_status', table_name='service_requests')
    op.drop_index('ix_requests_parent_order', table_name='service_requests')
    op.drop_index('ix_screenshots_request_id', table_name='screenshots')
    op.drop_constraint(None, 'request_types', type_='foreignkey')
    op.create_foreign_key(op.f('request_types_section_id_fkey'), 'request_types', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_request_screenshot_link', 'request_screenshot_links', type_='unique')
    op.drop_index('ix_screenshot_links_request_id', table_name='request_screenshot_links')
    op.drop_index('ix_request_resolutions_request_id', table_name='request_resolutions')
    op.drop_index('ix_request_notes_request_id', table_name='request_notes')
    op.drop_index('ix_request_notes_request_created', table_name='request_notes')
    op.drop_index('ix_request_assignees_unique', table_name='request_assignees')
    op.drop_index('ix_request_assignees_request_id', table_name='request_assignees')
    op.drop_index('ix_remote_sessions_request_id', table_name='remote_access_sessions')
    op.drop_index('ix_notification_events_request_id', table_name='notification_events')
    op.drop_constraint(None, 'chat_read_states', type_='foreignkey')
    op.alter_column('chat_read_states', 'request_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index('ix_messages_request_unread', table_name='chat_messages')
    op.drop_index('ix_messages_request_sender', table_name='chat_messages')
    op.drop_index('ix_messages_request_id', table_name='chat_messages')
    op.drop_index('ix_messages_request_created_desc', table_name='chat_messages')
    op.drop_index('ix_messages_request_created', table_name='chat_messages')
    op.drop_index('ix_chat_message_request_sequence', table_name='chat_messages')
    op.drop_column('chat_messages', 'client_temp_id')
    op.drop_index('ix_chat_files_request_id', table_name='chat_files')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.create_foreign_key(op.f('categories_section_id_fkey'), 'categories', 'sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_devices_state_source', table_name='devices')
    op.drop_index('ix_devices_lifecycle_state', table_name='devices')
    op.drop_index('ix_devices_hostname', table_name='devices')
    op.drop_index('ix_devices_discovery_source', table_name='devices')
    op.drop_index('ix_devices_desktop_session_id', table_name='devices')
    op.drop_index('ix_devices_created_at', table_name='devices')
    op.drop_table('devices')
    op.drop_index('ix_deployment_jobs_status_created', table_name='deployment_jobs')
    op.drop_index('ix_deployment_jobs_status', table_name='deployment_jobs')
    op.drop_index('ix_deployment_jobs_job_type', table_name='deployment_jobs')
    op.drop_index('ix_deployment_jobs_created_at', table_name='deployment_jobs')
    op.drop_table('deployment_jobs')
    op.drop_index('ix_credentials_type', table_name='credentials')
    op.drop_index('ix_credentials_name', table_name='credentials')
    op.drop_index('ix_credentials_enabled', table_name='credentials')
    op.drop_index('ix_credentials_created_at', table_name='credentials')
    op.drop_table('credentials')
    # ### end Alembic commands ###