"""make_desired_ous_nullable_in_active_directory_config

Revision ID: 7929f4845fee
Revises: 8578985fbd5c
Create Date: 2026-01-31 15:02:08.607201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7929f4845fee'
down_revision = '8578985fbd5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_directory_configs', 'desired_ous',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('active_directory_configs', 'desired_ous',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###